version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - front
    volumes:
      - wp-volume:/var/www/html
    restart: always
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - front
      - back
    restart: always
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - front
      - back
    volumes:
      - wp-volume:/var/www/html
    restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: /Users/kichlee/Desktop/inception/data/db
      type: none
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      device: /Users/kichlee/Desktop/inception/data/web
      type: none
      o: bind

networks:
  front:
    driver: bridge
  back:
    driver: bridge